version: "3.9"

services:
  eventx:
    build: .
    container_name: eventx-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app               # Sync local code for hot-reload
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: eventx-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: