version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: eventx-api-test
    command: npm run test
    environment:
      NODE_ENV: test
      JWT_SECRET: test-secret
    networks:
      - eventx-network

networks:
  eventx-network:
    driver: bridge
