version: "3.9"

services:
  eventx-api:
    container_name: eventx-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - eventx-network
    # depends_on:
    #   - mongo  
    restart: unless-stopped

  redis:
    container_name: eventx-redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - eventx-network
    restart: unless-stopped  

  # mongo:
  #   container_name: eventx-mongo
  #   image: mongo:7.0
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - backend  
  #   restart: unless-stopped  


volumes:
  mongo_data:


networks:
  eventx-network:
    driver: bridge
